#!/usr/bin/env python
# -*- coding: utf-8 -*-

import ConfigParser


"""In this file, we study the configparser"""

f_conf = ConfigParser.ConfigParser()
f_conf.read("nova.conf")

if not f_conf.has_section("__oslo_encrypt_config"):
    f_conf.add_section("__oslo_encrypt_config")
    
f_conf.set("__oslo_encrypt_config", "encrypted_keys", "user_password")

# write the result to nova-api.conf
with open("nova-api.conf", "w+") as f_conf_tmp:
    f_conf.write(f_conf_tmp)
